# Generated by Django 4.2.2 on 2023-06-21 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inspyme", "0002_userr"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Userr",
        ),
    ]
